imports:
    - { resource: parameters_prod.yml }
    - { resource: config.yml }

framework:
    validation:
# no APC extension on OVH 90 Plan
        cache:                         apc

doctrine:
    orm:
        entity_managers:
            default:
# no APC extension on OVH 90 Plan
#                metadata_cache_driver: apc
#                query_cache_driver:    apc
#                result_cache_driver:   apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:         stream
            path:         %kernel.logs_dir%/%kernel.name%_%kernel.environment%.log
            level:        debug
