# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#
# Support for LiipImagineBundle
#_imagine:
#    resource: .
#    type:     imagine

_front:
    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /admin

_api:
    resource: routing_api.yml
    prefix:   /api

#ryl_retirement:
#    resource: "@RylRetirementBundle/Resources/config/routing.xml"
#    prefix:   /retirement

#ryl_charity:
#    resource: "@RylCharityBundle/Resources/config/routing.xml"
#    prefix:   /charity

#ryl_reign_theme:
#    resource: "@RylReignThemeBundle/Resources/config/routing.xml"
#    prefix:   /
